# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8760e720738a05de86eaf0caab94c206"
name = "ESHAN Inventory Sync"
application_url = "https://example.com"
embedded = true

[access_scopes]
scopes = "read_products,write_products,read_inventory,write_inventory"

[auth]
redirect_urls = ["https://example.com/api/auth"]

[webhooks]
api_version = "2026-07"
