# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8760e720738a05de86eaf0caab94c206"
name = "ESHAN Inventory Sync"
application_url = "https://snowboard-sequence-justin-sounds.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_inventory,read_products,write_inventory,write_products"

[auth]
redirect_urls = ["https://snowboard-sequence-justin-sounds.trycloudflare.com/api/auth/callback"]
