# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f82dbdee74418429d3510c35ca99aae3"
name = "ESHAN Chennai Store"
application_url = "https://dz50mdfc-3000.inc1.devtunnels.ms"
embedded = true

[webhooks]
api_version = "2026-10"

[access_scopes]
scopes = "read_inventory,read_products,write_inventory,write_products"

[auth]
redirect_urls = ["https://dz50mdfc-3000.inc1.devtunnels.ms/api/auth/callback"]

[build]
automatically_update_urls_on_dev = true
